config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:      'public/publics/sessions',
    passwords:     'public/publics/passwords',
    registrations: 'public/publics/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admin/admins/sessions',
  }

  root to: 'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'search', to: 'searches#search'
  get 'search_genre', to: 'searches#search_genre'
  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end

  scope module: :public do
    resources :users, only: [:edit, :update, :show] do
      collection do
        get 'confirm'
        patch 'withdraw'
        post 'guest_sign_in', to: 'users#new_guest'
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings', to: 'relationships#followings', as: 'followings'
      get 'followers', to: 'relationships#followers', as: 'followers'
    end

    resources :posts, except: [:index, :destroy] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root 'homes#top'
    resources :users, only: [:edit, :update, :show]
    resources :posts, except: [:new, :index, :create]
    resources :genres, except: [:new, :destroy]
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:confirm, :back, :create]

  def new
    @contact = Contact.new
  end

  def confirm
    render :new if @contact.invalid?
  end

  def back
    render :new
  end

  def create
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      render :new
    end
  end

  def done; end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :message)
  end

  def set_contact
    @contact = Contact.new(contact_params)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="container">

  <div class="row my-4">
    <div class="col-md-4 offset-md-3">
      <h4>ご入力内容をご確認ください</h4>
    </div>
  </div>

  <div class="row my-4">
    <div class="col-md-3 offset-md-2 text-right">
      <h3>お名前</h3>
    </div>
    <div class="col">
      <h3><%= @contact.name %></h3>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-md-3 offset-md-2 text-right">
      <h4>メールアドレス</h4>
    </div>
    <div class="col">
      <h4><%= @contact.email %></h4>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-md-3 offset-md-2 text-right">
      <h3>メッセージ</h3>
    </div>
    <div class="col">
      <h3><%= @contact.message %></h3>
    </div>
  </div>

<%= form_with model: @contact, local: true do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :message %>
  <div class="my-4 offset-md-3">こちらの内容でよろしければ <%= f.submit "送信",class: "btn btn-success" %> を</div>
<% end %>
<%= form_with model: @contact, url: back_contacts_path,local: true do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :message %>
  <div class="my-4 offset-md-3">修正される場合は <%= f.submit "入力画面に戻る",class: "btn btn-primary" %> を押してください</div>
<% end %>

</div>

app/views/contacts/done.html.erb
<div class="container mt-4">
  <div class="row mt-4">
    <div class="mx-auto mt-4 text-center">
      <p style="font-size: 30px;">
        送信が完了いたしました。<br />
        お問い合わせ頂きましてありがとうございました。<br />
        引き続き当サイトをよろしくお願いいたします。<br />
        左上の当サイトアイコンよりTOPページへ遷移できます。
      </p>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= @contact.errors.count %>件の入力漏れがございます<br/>
    </h2>
    <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">

  <div class="row my-3">
    <div class="col-md-4 offset-md-4">
      <h1>お問い合わせ</h1>
    </div>
  </div>

  <div class="row my-3">
    <div class="col">
      <h3>
        サービスの品質向上のため、皆様からのお問い合わせをお待ちしております。<br />
        ジャンルの追加のご要望やご利用にあたって改善すべき点、欲しい機能など<br />
        お気づきの点がございましたら、以下にご記入ください。
      </h3>
    </div>
  </div>

<%= form_with model: @contact, url: confirm_contacts_path, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "お名前" %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email, "メールアドレス" %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :message, "メッセージ" %>
    <%= f.text_area :message,placeholder: "ジャンルの追加やその他ご意見・ご要望はこちらへ", size: "10x10", class: "form-control" %>
  </div>

  <div class="my-4">
    <%= f.submit "入力内容確認",class: "btn btn-success" %>
  </div>
<% end %>

</div>