config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:      'public/publics/sessions',
    passwords:     'public/publics/passwords',
    registrations: 'public/publics/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admin/admins/sessions',
  }

  root to: 'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'search', to: 'searches#search'
  get 'search_genre', to: 'searches#search_genre'
  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end

  scope module: :public do
    resources :users, only: [:edit, :update, :show] do
      collection do
        get 'confirm'
        patch 'withdraw'
        post 'guest_sign_in', to: 'users#new_guest'
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings', to: 'relationships#followings', as: 'followings'
      get 'followers', to: 'relationships#followers', as: 'followers'
    end

    resources :posts, except: [:index, :destroy] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root 'homes#top'
    resources :users, only: [:edit, :update, :show]
    resources :posts, except: [:new, :index, :create]
    resources :genres, except: [:new, :destroy]
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    @records = search_for(@model, @content, @method)
  end

  def search_genre
    @value = params['search']['value']
    @genre_records = search_genre_for(@value)
    @genre = Genre.find(@value)
  end

  private

  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.valid_user.where(name: content).or(User.valid_user.where(our_answers_id: content))
      elsif method == 'partial'
        User.valid_user.where('name LIKE ?', "%#{User.sanitize_sql_like(content)}%")
        .or(User.valid_user.where('our_answers_id LIKE ?', "%#{User.sanitize_sql_like(content)}%"))
      elsif method == 'forward'
        User.valid_user.where('name LIKE ?', "#{User.sanitize_sql_like(content)}%")
        .or(User.valid_user.where('our_answers_id LIKE ?', "#{User.sanitize_sql_like(content)}%"))
      elsif method == 'backward'
        User.valid_user.where('name LIKE ?', "%#{User.sanitize_sql_like(content)}")
        .or(User.valid_user.where('our_answers_id LIKE ?', "%#{User.sanitize_sql_like(content)}"))
      end
    elsif model == 'post'
      relations = [:user, :genre]
      if method == 'perfect'
        Post.includes(relations).showable.where(title: content)
        .or(Post.includes(relations).showable.where(body: content))
        .or(Post.includes(relations).showable.where(reference_url: content))
      elsif method == 'partial'
        Post.includes(relations).showable.where('title LIKE ?', "%#{Post.sanitize_sql_like(content)}%")
        .or(Post.includes(relations).showable.where('body LIKE ?', "%#{Post.sanitize_sql_like(content)}%"))
        .or(Post.includes(relations).showable.where('reference_url LIKE ?', "%#{Post.sanitize_sql_like(content)}%"))
      elsif method == 'forward'
        Post.includes(relations).showable.where('title LIKE ?', "#{Post.sanitize_sql_like(content)}%")
        .or(Post.includes(relations).showable.where('body LIKE ?', "#{Post.sanitize_sql_like(content)}%"))
        .or(Post.includes(relations).showable.where('reference_url LIKE ?', "#{Post.sanitize_sql_like(content)}%"))
      elsif method == 'backward'
        Post.includes(relations).showable.where('title LIKE ?', "%#{Post.sanitize_sql_like(content)}")
        .or(Post.includes(relations).showable.where('body LIKE ?', "%#{Post.sanitize_sql_like(content)}"))
        .or(Post.includes(relations).showable.where('reference_url LIKE ?', "%#{Post.sanitize_sql_like(content)}"))
      end
    end
  end

  def search_genre_for(value)
    Post.includes(:user).showable.where(genre_id: value)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_with url:search_path,method: :get, local: true do |f| %>
  <%= f.text_field :content %>
  <%= f.select :model, options_for_select([["投稿記事を検索","post"], ["ユーザーを検索","user"]]) %>
  <%= f.select :method, options_for_select([["完全一致","perfect"], ["部分一致","partial"], ["前方一致","forward"], ["後方一致","backward"]]) %>
  <%= f.submit "検索",class: "btn-warning" %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'user' %>
　<h4 class="search-word">ユーザー名orユーザーID <span class="result">"<%= @content %>"</span> での検索結果</h4>
　<%= render 'public/users/index', users: @records %>
<% elsif @model == 'post' %>
　<h4 class="search-word">投稿記事タイトルor記事詳細or参考url <span class="result">"<%= @content %>"</span> での検索結果</h4>
　<%= render 'public/posts/index', posts: @records %>
<% end %>

app/views/searches/search_genre.html.erb
 <h4 class="search-word">ジャンル <span class="result">"<%= @genre.name %>"</span> での検索結果</h4>
 <table class="table table-hover search-result">
  <thead>
    <tr>
      <th></th>
      <th>投稿日時</th>
      <th>タイトル</th>
      <th>参考記事url</th>
      <th>ブックマーク</th>
    </tr>
  </thead>
  <tbody>
    <% @genre_records.each do |record| %>
      <tr>
        <td class="text-center">
          <%= link_to user_path(record.user) do %>
            <%= attachment_image_tag(record.user, :profile_image, fallback: "no_image.jpg", size: "50x50", class: 'rounded-circle') %>
          <% end %><br />
          <%= record.user.name %>@<%= record.user.our_answers_id %>
        </td>
        <td><%= l record.created_at %></td>
        <td>
          <%= link_to record.title.truncate(20), post_path(record.id), class: "post_#{record.id}" %>
        </td>
        <td>
          <%= Rinku.auto_link(record.reference_url.truncate(30), :all, 'target="_blank"').html_safe %>
        </td>
        <td id="bookmark_form_<%= record.id %>">
          <% if user_signed_in? %>
            <% if record.user != current_user %>
              <%= render 'public/bookmarks/bookmark_form', post: record %>
            <% end %>
          <% else %>
            <%= record.bookmarks.count %>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>