config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:      'public/publics/sessions',
    passwords:     'public/publics/passwords',
    registrations: 'public/publics/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admin/admins/sessions',
  }

  root to: 'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'search', to: 'searches#search'
  get 'search_genre', to: 'searches#search_genre'
  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end

  scope module: :public do
    resources :users, only: [:edit, :update, :show] do
      collection do
        get 'confirm'
        patch 'withdraw'
        post 'guest_sign_in', to: 'users#new_guest'
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings', to: 'relationships#followings', as: 'followings'
      get 'followers', to: 'relationships#followers', as: 'followers'
    end

    resources :posts, except: [:index, :destroy] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root 'homes#top'
    resources :users, only: [:edit, :update, :show]
    resources :posts, except: [:new, :index, :create]
    resources :genres, except: [:new, :destroy]
  end

end

app/views/layouts/_admin_signed_in_bar.html.erb
<li><%= link_to "ジャンル一覧", admin_genres_path,class: 'nav-link active' %></li>
<li><%= link_to "会員一覧", admin_root_path,class: 'nav-link active' %></li>
<li><%= link_to "ログアウト", destroy_admin_session_path,class: 'nav-link active', method: :delete %></li>

app/views/layouts/_user_signed_in_bar.html.erb
<li>
  <%= link_to user_path(current_user),class: 'nav-link active' do %>
    <i class="fas fa-user faa-float animated-hover"></i> マイページ
  <% end %>
</li>
<li>
  <%= link_to new_post_path,class: 'nav-link active' do %>
    <i class="fas fa-plus-circle faa-spin animated-hover"></i> 新規記事投稿
  <% end %>
</li>
<li>
  <%= link_to notifications_path, class: 'nav-link active' do %>
    <i class="fas fa-bell faa-tada animated-hover"></i> 通知
    <% if unchecked_notifications.any? %>
      <i class="fas fa-circle" style="color: gold;"></i>
    <% end %>
  <% end %>
</li>
<li>
  <%= link_to destroy_user_session_path,class: 'nav-link active', method: :delete do %>
    <i class="fas fa-sign-out-alt faa-passing animated-hover"></i> ログアウト
  <% end %>
</li>
<li>
  <%= link_to about_path,class: 'nav-link active' do %>
    <i class="fas fa-question-circle faa-pulse animated-hover"></i> 当サイトについて
  <% end %>
</li>

app/views/layouts/_user_signed_out_bar.html.erb
<li>
  <%= link_to new_user_registration_path,class: 'nav-link active' do %>
    <i class="fas fa-user-plus"></i> 新規登録
  <% end %>
</li>
<li>
  <%= link_to new_user_session_path,class: 'nav-link active' do %>
    <i class="fas fa-sign-in-alt"></i> ログイン
  <% end %>
</li>
<li><%= link_to 'ゲストログイン(閲覧用)',guest_sign_in_users_path, class: "guest-login nav-link active", method: :post %></li>
<li>
  <%= link_to about_path,class: 'nav-link active' do %>
    <i class="fas fa-question-circle"></i> 当サイトについて
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OurAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.2.1/font-awesome-animation.css" type="text/css" media="all" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDropdown" aria-controls="navbarTogglerDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a id="app-title" class="navbar-brand" href="/">Our Answer</a>
          <%= render 'searches/form' %>
        <div class="collapse navbar-collapse" id="navbarTogglerDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <%= render "layouts/user_signed_in_bar" %>
            <% elsif admin_signed_in? %>
              <%= render "layouts/admin_signed_in_bar" %>
            <% else %>
              <%= render "layouts/user_signed_out_bar" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main class="background">
    <%= yield %>
    <div id="page_top"><a href="#"><i class="fas fa-chevron-up"></i></a></div>

  </main>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <footer class="footer m-auto">
        <div class="container">
          <ul class="navbar-nav">
            <li class="nav-item">© 2021 Yuya Sawata</li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <%= link_to new_contact_path,class: 'nav-link active' do %>
              <li class="nav-item">　　　　　お問い合わせはこちら＞</li>
            <% end %>
          </ul>
        </div>
      </footer>
    </nav>
  </body>
</html>